system {
    host-name r1;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.0.12.1/30;
            }
            family iso;
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.0.13.1/30;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.0.0.1/32;
            }
            family iso {
                address 49.0001.0100.0000.0001.00;
            }
        }
    }
}
routing-options {
    router-id 10.0.0.1;
}
protocols {
    isis {
        interface ge-0/0/0.0 {
            level 1 disable;
        }
        interface ge-0/0/1.0 {
            level 2 disable;
        }
        interface lo0.0 {
            passive;
        }
        export leak-l2-to-l1;
    }
}
policy-options {
    policy-statement leak-l2-to-l1 {
        term 1 {
            from {
                protocol isis;
                level 2;
            }
            then reject;
        }
    }
}
