system {
    host-name r5;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 192.168.35.2/24;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 192.168.56.1/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 5.5.5.5/32;
            }
            family iso {
                address 49.0002.0050.0500.5005.00;
            }
        }
    }
}
routing-options {
    router-id 5.5.5.5;
}