system {
    host-name r10;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.9.10.2/30;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.6.10.2/30;
            }
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 10.5.10.2/30;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.0.0.10/32;
            }
        }
    }
}
routing-options {
    router-id 10.0.0.10;
    autonomous-system 65000;
}
protocols {
    ospf {
        area 0.0.0.0 {
            interface ge-0/0/0.0 {
                bfd-liveness-detection {
                    minimum-interval 300;
                    multiplier 3;
                }
            }
            interface ge-0/0/1.0 {
                bfd-liveness-detection {
                    minimum-interval 300;
                    multiplier 3;
                }
            }
            interface ge-0/0/2.0 {
                bfd-liveness-detection {
                    minimum-interval 300;
                    multiplier 3;
                }
            }
            interface lo0.0 {
                passive;
            }
        }
    }
    bgp {
        group ibgp {
            type internal;
            local-address 10.0.0.10;
            neighbor 10.0.0.1;
            neighbor 10.0.0.2;
            neighbor 10.0.0.3;
            neighbor 10.0.0.4;
            neighbor 10.0.0.5;
            neighbor 10.0.0.6;
            neighbor 10.0.0.7;
            neighbor 10.0.0.8;
            neighbor 10.0.0.9;
        }
    }
}
