system {
    host-name r2;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.0.12.2/30;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.0.24.1/30;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.0.0.2/32;
            }
        }
    }
}
routing-options {
    router-id 10.0.0.2;
}
protocols {
    ospf {
        area 0.0.0.0 {
            interface ge-0/0/0.0;
            interface ge-0/0/1.0;
            interface lo0.0 {
                passive;
            }
        }
    }
    bgp {
        local-as 65001;
        group EBGP {
            type external;
            peer-as 65002;
            neighbor 10.0.24.2 {
                description "r4";
            }
        }
        group IBGP {
            type internal;
            local-address 10.0.0.2;
            neighbor 10.0.0.1 {
                description "r1";
            }
        }
    }
}
policy-options {
    policy-statement advertise-loopback {
        term 1 {
            from {
                protocol direct;
                route-filter 10.0.0.2/32 exact;
            }
            then accept;
        }
        term 2 {
            then reject;
        }
    }
}
