system {
    host-name r2;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.0.12.2/30;
            }
            family iso;
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.0.24.1/30;
            }
            family iso;
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.0.0.2/32;
            }
            family iso {
                address 49.0001.0100.0000.0002.00;
            }
        }
    }
}
routing-options {
    router-id 10.0.0.2;
}
protocols {
    isis {
        interface ge-0/0/0.0 {
            level 1 disable;
        }
        interface ge-0/0/1.0 {
            level 1 disable;
        }
        interface lo0.0 {
            passive;
        }
    }
}
