system {
    host-name r1;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 172.31.0.1/30;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 172.31.13.1/30;
            }
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 172.31.14.1/30;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 1.1.1.1/32;
            }
        }
    }
}
routing-options {
    router-id 1.1.1.1;
}
