system {
    host-name r4;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 172.31.14.2/30;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 172.31.24.2/30;
            }
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 172.31.45.1/30;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 4.4.4.4/32;
            }
        }
    }
}
routing-options {
    router-id 4.4.4.4;
}
