system {
    host-name r5;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 172.31.56.1/30;
            }
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 172.31.45.2/30;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 5.5.5.5/32;
            }
        }
    }
}
routing-options {
    router-id 5.5.5.5;
}
