system {
    host-name r6;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 172.31.56.2/30;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 172.31.67.1/30;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 6.6.6.6/32;
            }
        }
    }
}
routing-options {
    router-id 6.6.6.6;
}
