system {
    host-name r1;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 192.168.12.1/24;
            }
            family inet6 {
                address 2001:12:dead:beef::1/64;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 192.168.17.1/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 1.1.1.1/32;
            }
        }
    }
}
routing-options {
    router-id 1.1.1.1;
}
