system {
    host-name r4;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 172.16.24.4/24;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 172.16.34.4/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 12.12.12.12/32;
            }
        }
    }
}
routing-options {
    router-id 12.12.12.12;
}
