system {
    host-name r6;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.56.56.6/24;
            }
            family inet6 {
                address 2005:56:dead:beef::6/64;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 192.168.68.6/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 6.6.6.6/32;
            }
        }
    }
}
routing-options {
    router-id 6.6.6.6;
}
