system {
    host-name r4;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        description "to-r3";
        unit 0 {
            family inet {
                address 10.0.34.2/30;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.0.0.4/32;
            }
        }
    }
}
routing-options {
    router-id 10.0.0.4;
}
