system {
    host-name pe4;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 192.168.45.1/24;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 192.168.34.2/24;
            }
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 172.168.34.2/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 4.4.4.4/32;
            }
            family iso {
                address 49.0000.0040.0400.4004.00
            }
        }
    }
}
routing-options {
    router-id 4.4.4.4;
}