system {
    host-name sw4;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family ethernet-switching {
                interface-mode trunk;
                vlan {
                    members [ VLAN10 VLAN20 VLAN30 ];
                }
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family ethernet-switching {
                interface-mode trunk;
                vlan {
                    members [ VLAN10 VLAN20 VLAN30 ];
                }
            }
        }
    }
    irb {
        unit 10 {
            family inet {
                address 192.168.10.2/24;
                vrrp-group 10 {
                    virtual-address 192.168.10.254;
                    priority 100;
                    preempt;
                }
            }
        }
    }
}
vlans {
    VLAN10 {
        vlan-id 10;
        l3-interface irb.10;
    }
    VLAN20 {
        vlan-id 20;
    }
    VLAN30 {
        vlan-id 30;
    }
}
protocols {
    rstp {
        bridge-priority 32768;
        interface ge-0/0/0.0;
        interface ge-0/0/1.0;
    }
}
