system {
    host-name sw3;
    services {
        ssh;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family ethernet-switching {
                interface-mode trunk;
                vlan {
                    members [ VLAN10 VLAN20 ];
                }
            }
        }
    }
    ge-0/0/3 {
        unit 0 {
            family ethernet-switching {
                interface-mode access;
                vlan {
                    members VLAN30;
                }
            }
        }
    }
}
vlans {
    VLAN10 {
        vlan-id 10;
    }
    VLAN20 {
        vlan-id 20;
    }
    VLAN30 {
        vlan-id 30;
    }
}
protocols {
    rstp {
        bridge-priority 32768;
        interface ge-0/0/0.0;
    }
}
